### ISSUE TITLE
WARNING: sanity [sanity.c:612]: check_cl(): content length header missing in request

### ISSUE THREAD

**Issue by sonkimsour** [os11k/dispatcher#3]
I have tested the kamailio.cfg, but have rejected by Freeswitch, such as registration is not working as details below:
/usr/sbin/kamailio[12009]: WARNING: sanity [sanity.c:612]: check_cl(): content length header missing in request

**Comment by os11k** [comment]
Hi! It is insufficient to understand what happening with 1 line of logs. Please attach full logs from Kamailio & Freesiwtch.

**Comment by os11k** [comment]
Closing
