### ISSUE TITLE
Getting error messages in logs

### ISSUE THREAD

**Issue by balaji07s** [os11k/dispatcher#4]
Hi, 

 I have recently installed kamailio on my linux debian and while making calls it is showing errors in the logs. Kindly help me with this.

Oct 30 18:11:41 balaji-Virtualbox kamailio[2781]: 27(2781) ERROR: {2 2 INVITE PS1XPCblBqE35MWzOu8awA..} db_mysql [km_dbase.c:122]: db_mysql_submit_query(): driver error on query: Unknown column 'src_user' in 'field list' (1054)
Oct 30 18:11:41 balaji-Virtualbox kamailio[2781]: 27(2781) ERROR: {2 2 INVITE PS1XPCblBqE35MWzOu8awA..} <core> [db_query.c:244]: db_do_insert_cmd(): error while submitting query
Oct 30 18:11:41 balaji-Virtualbox kamailio[2781]: 27(2781) ERROR: {2 2 INVITE PS1XPCblBqE35MWzOu8awA..} acc [acc.c:490]: acc_db_request(): failed to insert into database
Oct 30 18:12:07 balaji-Virtualbox kamailio[2783]: 29(2783) NOTICE: {2 3 BYE PS1XPCblBqE35MWzOu8awA..} acc [acc.c:287]: acc_log_request(): ACC: transaction answered: timestamp=1635597727;method=BYE;from_tag=eb9fe459;to_tag=xy0ppd4;call_id=PS1XPCblBqE35MWzOu8awA..;code=200;reason=Ok;src_user=123;src_domain=192.168.1.8;src_ip=192.168.1.3;dst_ouser=456;dst_user=456;dst_domain=192.168.1.4
Oct 30 18:12:07 balaji-Virtualbox kamailio[2783]: 29(2783) ERROR: {2 3 BYE PS1XPCblBqE35MWzOu8awA..} db_mysql [km_dbase.c:122]: db_mysql_submit_query(): driver error on query: Unknown column 'src_user' in 'field list' (1054)
Oct 30 18:12:07 balaji-Virtualbox kamailio[2783]: 29(2783) ERROR: {2 3 BYE PS1XPCblBqE35MWzOu8awA..} <core> [db_query.c:244]: db_do_insert_cmd(): error while submitting query
Oct 30 18:12:07 balaji-Virtualbox kamailio[2783]: 29(2783) ERROR: {2 3 BYE PS1XPCblBqE35MWzOu8awA..} acc [acc.c:490]: acc_db_request(): failed to insert into database

Thanks,
Balaji

**Comment by os11k** [comment]
This is related to ACC module it can't insert some data to DB. Do you need it? If not, disabling it will fix this problem. Just remove `#!define WITH_ACCDB` line from your config file, if you are using default one.

**Comment by balaji07s** [comment]
okay thanks @os11k

**Comment by balaji07s** [comment]
Hi @os11k can you please tell what if i want the data to be stored in the database without any error?
can you confirm Is this error coming because of the problem with the ACC module or the database?
Any solution for this other than disabling the ACC module?

Thanks,
Balaji

**Comment by os11k** [comment]
Hi,

Based on error: "Unknown column 'src_user' in 'field list'", seems you don't have table for the data you want to insert or table don't have columns what you need. So I would recommend you to recheck your MySQL database tables.

**Comment by balaji07s** [comment]
Thanks, @os11k for your help.

**Comment by balaji07s** [comment]
Hi @os11k ,
      I need one last help from you. When i use my softphone to connect to my sip server it shows like this in logs.

**Nov 08 15:15:42 balaji-VirtualBox /usr/sbin/kamailio[11888]: ERROR: {1 2 REGISTER -QrxbmV_T-7XTiQwwegtDg..} <core> [db_query.c:141]: db_do_query_internal(): error while submitting query
Nov 08 15:15:42 balaji-VirtualBox /usr/sbin/kamailio[11888]: ERROR: {1 2 REGISTER -QrxbmV_T-7XTiQwwegtDg..} auth_db [authorize.c:178]: get_ha1(): failed to query database
Nov 08 15:15:42 balaji-VirtualBox /usr/sbin/kamailio[11891]: ERROR: {1 2 SUBSCRIBE XqES1HiRYhKUCBuWXKVTPw..} db_mysql [km_dbase.c:122]: db_mysql_submit_query(): driver error on query: Connection was killed (1927)
Nov 08 15:15:42 balaji-VirtualBox /usr/sbin/kamailio[11891]: ERROR: {1 2 SUBSCRIBE XqES1HiRYhKUCBuWXKVTPw..} <core> [db_query.c:141]: db_do_query_internal(): error while submitting query
Nov 08 15:15:42 balaji-VirtualBox /usr/sbin/kamailio[11891]: ERROR: {1 2 SUBSCRIBE XqES1HiRYhKUCBuWXKVTPw..} auth_db [authorize.c:178]: get_ha1(): failed to query database
Nov 08 15:20:22 balaji-VirtualBox /usr/sbin/kamailio[11899]: INFO: {1 2 REGISTER Wu1vEhl8oF13dC2vHtlrGw..} db_mysql [km_dbase.c:84]: db_mysql_submit_query(): driver error on ping: Connection was killed
Nov 08 15:20:22 balaji-VirtualBox /usr/sbin/kamailio[11900]: INFO: {1 2 SUBSCRIBE GVH5nc_0WggeUX-thck_KQ..} db_mysql [km_dbase.c:84]: db_mysql_submit_query(): driver error on ping: Connection was killed
Nov 08 15:20:22 balaji-VirtualBox /usr/sbin/kamailio[11889]: INFO: {1 3 REGISTER Wu1vEhl8oF13dC2vHtlrGw..} db_mysql [km_dbase.c:84]: db_mysql_submit_query(): driver error on ping: Connection was killed
Nov 08 15:20:56 balaji-VirtualBox /usr/sbin/kamailio[11913]: INFO: db_mysql [km_dbase.c:84]: db_mysql_submit_query(): driver error on ping: Connection was killed
Nov 08 15:23:04 balaji-VirtualBox /usr/sbin/kamailio[11893]: INFO: {1 5 REGISTER Wu1vEhl8oF13dC2vHtlrGw..} db_mysql [km_dbase.c:84]: db_mysql_submit_query(): driver error on ping: Connection was killed
**

can you please tell me why this error is coming in logs while registering?

Thank you

**Comment by os11k** [comment]
Hi @balaji07s , seems something with DB, I can't tell you more then that.

**Comment by os11k** [comment]
Will close this issue, because it is nothing to do with code in this repository.
