### ISSUE TITLE
dispatcher 2 asterisk

### ISSUE THREAD

**Issue by kietcaodev** [os11k/dispatcher#5]
hi Guy,
i config my kamailio with his config, and it working 1 kamailio --> dispatcher 1 asterisk
i register 2 my sip asterisk account via kamailio work fine.
But i config my kamailio with his config, and it working 1 kamailio --> dispatcher 2 asterisk(loadbalancing), it not working , i can't register and call two between 2 device

**Comment by os11k** [comment]
I don't understood, what you wrote. Can you please explain where problem is?

**Comment by kietcaodev** [comment]
![image](https://user-images.githubusercontent.com/71913797/199917584-be434487-a8aa-43cb-b752-ddab2a16f0c5.png)
i have 1 kamailio-172.23.90.124 config module dispatcher load balancing 2 asterisk server 172.23.90.171,172.23.90.172
when i register device , it not working

**Comment by kietcaodev** [comment]
if i have 1 server kamailio config module dispatcher and 1 server asterisk. i register successful
![image](https://user-images.githubusercontent.com/71913797/199918441-042aa0c5-a657-4f36-940b-6bb54fcff7cb.png)

**Comment by os11k** [comment]
I think it is due that Asterisks do not share registrations. Other solution would be to try out hash over authorization-username:

```
if(!ds_select_dst("1", "5")
```

**Comment by kietcaodev** [comment]
many tks , i will try it

**Comment by os11k** [comment]
Actually I think it should be hash over call-id:

```
if(!ds_select_dst("1", "0")
```

That means all messages with same call-id will be sent to same asterisk, that what we are trying to achieve here... I suppose

With hash over authorization-username it will not work, because first registration will not have authorization-username...

**Comment by os11k** [comment]
Hi! Did you get it work? I will close this issue in next couple of days if no reply will be received.

**Comment by kietcaodev** [comment]
it's working. Many tks @os11k . 
Have a good day for you
